In [2]:
from pathlib import Path
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

PROJECT_ROOT = Path("/store/users/xu/2025_MSc_b2b/roamm")

INPUT__PATH = (PROJECT_ROOT / "outputs" / "roamm_words_with_length_and_frequency.csv")

words = pd.read_csv(INPUT__PATH, keep_default_na=False)

words.shape

(10839, 10)

In [3]:
words.head()

,story_name,page,sentence_id,sentence,word_position,words,word_key,normalized_word,word_length,frequency_zipf
0,history_of_film,0,history_of_film_0,"The history of film began in the 1890s, with t...",0,The,4f29e384-84f8-4dc8-bd07-e4d351038c53,The,3,7.73
1,history_of_film,0,history_of_film_0,"The history of film began in the 1890s, with t...",1,history,1d6ed8cf-e2b5-43ce-b190-56f8ec83d14c,history,7,5.39
2,history_of_film,0,history_of_film_0,"The history of film began in the 1890s, with t...",2,of,7e7b8839-ee21-47ac-8a31-9d078a751723,of,2,7.4
3,history_of_film,0,history_of_film_0,"The history of film began in the 1890s, with t...",3,film,e5f11c54-eed2-4a3d-b843-2f75c9632a48,film,4,5.2
4,history_of_film,0,history_of_film_0,"The history of film began in the 1890s, with t...",4,began,db267961-974c-491a-8f3f-74e3f819920f,began,5,5.07

In [4]:
words.groupby("sentence_id")["story_name"].nunique().max()

np.int64(1)

In [5]:
words[
    ["story_name", "sentence_id", "word_position", "words", "sentence"]
].head(30)

,story_name,sentence_id,word_position,words,sentence
0,history_of_film,history_of_film_0,0,The,"The history of film began in the 1890s, with t..."
1,history_of_film,history_of_film_0,1,history,"The history of film began in the 1890s, with t..."
2,history_of_film,history_of_film_0,2,of,"The history of film began in the 1890s, with t..."
3,history_of_film,history_of_film_0,3,film,"The history of film began in the 1890s, with t..."
4,history_of_film,history_of_film_0,4,began,"The history of film began in the 1890s, with t..."
5,history_of_film,history_of_film_0,5,in,"The history of film began in the 1890s, with t..."
6,history_of_film,history_of_film_0,6,the,"The history of film began in the 1890s, with t..."
7,history_of_film,history_of_film_0,7,"1890s,","The history of film began in the 1890s, with t..."
8,history_of_film,history_of_film_0,8,with,"The history of film began in the 1890s, with t..."
9,history_of_film,history_of_film_0,9,the,"The history of film began in the 1890s, with t..."
10,history_of_film,history_of_film_0,10,invention,"The history of film began in the 1890s, with t..."
11,history_of_film,history_of_film_0,11,of,"The history of film began in the 1890s, with t..."
12,history_of_film,history_of_film_0,12,motion,"The history of film began in the 1890s, with t..."
13,history_of_film,history_of_film_0,13,picture,"The history of film began in the 1890s, with t..."
14,history_of_film,history_of_film_0,14,cameras,"The history of film began in the 1890s, with t..."
15,history_of_film,history_of_film_0,15,and,"The history of film began in the 1890s, with t..."
16,history_of_film,history_of_film_0,16,the,"The history of film began in the 1890s, with t..."
17,history_of_film,history_of_film_0,17,establishment,"The history of film began in the 1890s, with t..."
18,history_of_film,history_of_film_0,18,of,"The history of film began in the 1890s, with t..."
19,history_of_film,history_of_film_0,19,film,"The history of film began in the 1890s, with t..."
20,history_of_film,history_of_film_0,20,production,"The history of film began in the 1890s, with t..."
21,history_of_film,history_of_film_0,21,companies.,"The history of film began in the 1890s, with t..."
22,history_of_film,history_of_film_1,22,The,The films of the 1890s were under a minute lon...
23,history_of_film,history_of_film_1,23,films,The films of the 1890s were under a minute lon...
24,history_of_film,history_of_film_1,24,of,The films of the 1890s were under a minute lon...
25,history_of_film,history_of_film_1,25,the,The films of the 1890s were under a minute lon...
26,history_of_film,history_of_film_1,26,1890s,The films of the 1890s were under a minute lon...
27,history_of_film,history_of_film_1,27,were,The films of the 1890s were under a minute lon...
28,history_of_film,history_of_film_1,28,under,The films of the 1890s were under a minute lon...
29,history_of_film,history_of_film_1,29,a,The films of the 1890s were under a minute lon...

In [9]:
sentence_id = "pluto_0"

sentence_df = (words[words["sentence_id"] == sentence_id].sort_values("word_position"))
sentence_df[["word_position", "words", "sentence"]]

,word_position,words,sentence
2141,0,Pluto,Pluto (minor-planet designation: 134340 Pluto)...
2142,1,(minor-planet,Pluto (minor-planet designation: 134340 Pluto)...
2143,2,designation:,Pluto (minor-planet designation: 134340 Pluto)...
2144,3,134340,Pluto (minor-planet designation: 134340 Pluto)...
2145,4,Pluto),Pluto (minor-planet designation: 134340 Pluto)...
2146,5,is,Pluto (minor-planet designation: 134340 Pluto)...
2147,6,a,Pluto (minor-planet designation: 134340 Pluto)...
2148,7,dwarf,Pluto (minor-planet designation: 134340 Pluto)...
2149,8,planet,Pluto (minor-planet designation: 134340 Pluto)...
2150,9,in,Pluto (minor-planet designation: 134340 Pluto)...
2151,10,the,Pluto (minor-planet designation: 134340 Pluto)...
2152,11,Kuiper,Pluto (minor-planet designation: 134340 Pluto)...
2153,12,"belt,",Pluto (minor-planet designation: 134340 Pluto)...
2154,13,a,Pluto (minor-planet designation: 134340 Pluto)...
2155,14,ring,Pluto (minor-planet designation: 134340 Pluto)...
2156,15,of,Pluto (minor-planet designation: 134340 Pluto)...
2157,16,bodies,Pluto (minor-planet designation: 134340 Pluto)...
2158,17,beyond,Pluto (minor-planet designation: 134340 Pluto)...
2159,18,Neptune.,Pluto (minor-planet designation: 134340 Pluto)...

In [10]:
original_words = sentence_df["words"].tolist()

reconstructed = " ".join(original_words)
original_sentence = sentence_df["sentence"].iloc[0]

print("Original:")
print(original_sentence)

print("\nReconstructed:")
print(reconstructed)

print("\nSame:")
print(original_sentence == reconstructed)

Original:
Pluto (minor-planet designation: 134340 Pluto) is a dwarf planet in the Kuiper belt, a ring of bodies beyond Neptune.

Reconstructed:
Pluto (minor-planet designation: 134340 Pluto) is a dwarf planet in the Kuiper belt, a ring of bodies beyond Neptune.

Same:
True

In [11]:
tokenizer = AutoTokenizer.from_pretrained(
    "gpt2",
    use_fast=True
)

encoded = tokenizer(
    reconstructed,
    return_offsets_mapping=True,
    add_special_tokens=False
)

tokens = tokenizer.convert_ids_to_tokens(
    encoded["input_ids"]
)

offsets = encoded["offset_mapping"]

for token, offset in zip(tokens, offsets):
    print(token, offset)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Pl (0, 2)
uto (2, 5)
Ġ( (5, 7)
min (7, 10)
or (10, 12)
- (12, 13)
planet (13, 19)
Ġdesignation (19, 31)
: (31, 32)
Ġ13 (32, 35)
43 (35, 37)
40 (37, 39)
ĠPluto (39, 45)
) (45, 46)
Ġis (46, 49)
Ġa (49, 51)
Ġdwarf (51, 57)
Ġplanet (57, 64)
Ġin (64, 67)
Ġthe (67, 71)
ĠK (71, 73)
ui (73, 75)
per (75, 78)
Ġbelt (78, 83)
, (83, 84)
Ġa (84, 86)
Ġring (86, 91)
Ġof (91, 94)
Ġbodies (94, 101)
Ġbeyond (101, 108)
ĠNeptune (108, 116)
. (116, 117)

In [12]:
text = ""
word_spans = []

for word in original_words:
    if text:
        text += " "

    start = len(text)
    text += word
    end = len(text)

    word_spans.append((start, end))

In [13]:
for word, span in zip(original_words, word_spans):
    print(word, span)

Pluto (0, 5)
(minor-planet (6, 19)
designation: (20, 32)
134340 (33, 39)
Pluto) (40, 46)
is (47, 49)
a (50, 51)
dwarf (52, 57)
planet (58, 64)
in (65, 67)
the (68, 71)
Kuiper (72, 78)
belt, (79, 84)
a (85, 86)
ring (87, 91)
of (92, 94)
bodies (95, 101)
beyond (102, 108)
Neptune. (109, 117)

In [10]:
from pathlib import Path
import pandas as pd
import numpy as np

file = Path(
    "/scratch/data/ROAMM/derivatives/synced/"
    "sub-10014/"
    "sub-10014_task-ReMind_run-01_mldata.pkl"
)

df = pd.read_pickle(file)

df.shape

(168704, 139)

In [3]:
fix = df.loc[
    df["first_pass_reading"].eq(True)
    & df["fix_R_tStart"].notna()
].copy()

fix[
    ["time", "fix_R_tStart", "fix_R_fixed_word"]
].head()

           time  fix_R_tStart fix_R_fixed_word
3215  12.558594     12.220262              NaN
3216  12.562500     12.220262              NaN
3217  12.566406     12.220262              NaN
3218  12.570312     12.220262              NaN
3219  12.574219     12.220262              NaN

In [4]:
fix_events = (
    fix
    .drop_duplicates("fix_R_tStart")
    .copy()
)

fix_events[
    ["time", "fix_R_tStart", "fix_R_fixed_word"]
].head()

           time  fix_R_tStart fix_R_fixed_word
3215  12.558594     12.220262              NaN
3316  12.953125     12.949263          volume.
3393  13.253906     13.253262          volume.
3437  13.425781     13.424263    (minor-planet
3479  13.589844     13.589262            Pluto

In [5]:
fix_events["eeg_sample"] = fix_events.index

In [6]:
fix_events["sync_error_ms"] = (
    fix_events["time"] - fix_events["fix_R_tStart"]
) * 1000

In [7]:
fix_events[
    [
        "eeg_sample",
        "time",
        "fix_R_tStart",
        "sync_error_ms",
        "fix_R_fixed_word",
    ]
].head(20)

      eeg_sample       time  fix_R_tStart  sync_error_ms fix_R_fixed_word
3215        3215  12.558594     12.220262      338.33125              NaN
3316        3316  12.953125     12.949263        3.86250          volume.
3393        3393  13.253906     13.253262        0.64375          volume.
3437        3437  13.425781     13.424263        1.51875    (minor-planet
3479        3479  13.589844     13.589262        0.58125            Pluto
3522        3522  13.757812     13.757263        0.55000            Pluto
3580        3580  13.984375     13.983263        1.11250    (minor-planet
3635        3635  14.199219     14.196262        2.95625    (minor-planet
3699        3699  14.449219     14.447262        1.95625     designation:
3749        3749  14.644531     14.644262        0.26875           134340
3805        3805  14.863281     14.861263        2.01875           Pluto)
3865        3865  15.097656     15.097263        0.39375            dwarf
3937        3937  15.378906     15.377263        1.64375           planet
3991        3991  15.589844     15.589262        0.58125           Kuiper
4048        4048  15.812500     15.809263        3.23750              the
4096        4096  16.000000     15.998262        1.73750           Kuiper
4149        4149  16.207031     16.206262        0.76875           Kuiper
4241        4241  16.566406     16.565262        1.14375            belt,
4277        4277  16.707031     16.704263        2.76875            Pluto
4369        4369  17.066406     17.063263        3.14375    (minor-planet

In [8]:
fix_events["sync_error_ms"].abs().max()

np.float64(914.4875000000638)

In [21]:
from pathlib import Path
import pandas as pd
import numpy as np

pkl_path = Path(
    "/scratch/data/ROAMM/derivatives/synced/"
    "sub-10111/sub-10111_task-ReMind_run-05_mldata.pkl"
)

df = pd.read_pickle(pkl_path)

In [22]:
list(df.columns[:64])

['Fp1',
 'AF7',
 'AF3',
 'F1',
 'F3',
 'F5',
 'F7',
 'FT7',
 'FC5',
 'FC3',
 'FC1',
 'C1',
 'C3',
 'C5',
 'T7',
 'TP7',
 'CP5',
 'CP3',
 'CP1',
 'P1',
 'P3',
 'P5',
 'P7',
 'P9',
 'PO7',
 'PO3',
 'O1',
 'Iz',
 'Oz',
 'POz',
 'Pz',
 'CPz',
 'Fpz',
 'Fp2',
 'AF8',
 'AF4',
 'Afz',
 'Fz',
 'F2',
 'F4',
 'F6',
 'F8',
 'FT8',
 'FC6',
 'FC4',
 'FC2',
 'FCz',
 'Cz',
 'C2',
 'C4',
 'C6',
 'T8',
 'TP8',
 'CP6',
 'CP4',
 'CP2',
 'P2',
 'P4',
 'P6',
 'P8',
 'P10',
 'PO8',
 'PO4',
 'O2']

In [23]:
EEG_CHANNELS = [
    "Fp1", "AF7", "AF3", "F1", "F3", "F5", "F7", "FT7",
    "FC5", "FC3", "FC1", "C1", "C3", "C5", "T7", "TP7",
    "CP5", "CP3", "CP1", "P1", "P3", "P5", "P7", "P9",
    "PO7", "PO3", "O1", "Iz", "Oz", "POz", "Pz", "CPz",
    "Fpz", "Fp2", "AF8", "AF4", "Afz", "Fz", "F2", "F4",
    "F6", "F8", "FT8", "FC6", "FC4", "FC2", "FCz", "Cz",
    "C2", "C4", "C6", "T8", "TP8", "CP6", "CP4", "CP2",
    "P2", "P4", "P6", "P8", "P10", "PO8", "PO4", "O2",
]

In [24]:
assert list(df.columns[:64]) == EEG_CHANNELS

In [25]:
eeg = np.load(
    "/scratch/data/ROAMM/outputs/eeg/sub-10111_run5_eeg.npy"
)

eeg.shape

(64, 198912)

In [26]:
for i, ch in enumerate(EEG_CHANNELS):
    assert np.allclose(
        eeg[i],
        df[ch].to_numpy()
    )

print("All EEG channels match.")

All EEG channels match.

# check left and eye fixations

In [1]:
import pandas as pd
from pathlib import Path

path = Path(
    "/scratch/data/ROAMM/derivatives/synced/"
    "sub-10014/sub-10014_task-ReMind_run-01_mldata.pkl"
)

df = pd.read_pickle(path)

print("Shape:", df.shape)
print("Number of columns:", len(df.columns))

Shape: (168704, 139)
Number of columns: 139

In [2]:
fix_cols = [
    col for col in df.columns
    if col.startswith("fix_")
]

print(fix_cols)

['fix_L_eye', 'fix_L_tStart', 'fix_L_tEnd', 'fix_L_duration', 'fix_L_xAvg', 'fix_L_yAvg', 'fix_L_pupilAvg', 'fix_L_fixed_word', 'fix_L_fixed_word_key', 'fix_R_eye', 'fix_R_tStart', 'fix_R_tEnd', 'fix_R_duration', 'fix_R_xAvg', 'fix_R_yAvg', 'fix_R_pupilAvg', 'fix_R_fixed_word', 'fix_R_fixed_word_key']

In [3]:
for eye in ["L", "R"]:
    onset_col = f"fix_{eye}_tStart"
    word_col = f"fix_{eye}_fixed_word_key"

    events = (
        df[[onset_col, word_col]]
        .dropna(subset=[onset_col])
        .drop_duplicates(subset=[onset_col])
    )

    print(
        f"{eye} eye:",
        len(events), "fixations,",
        events[word_col].notna().sum(), "mapped to words"
    )

L eye: 2558 fixations, 790 mapped to words
R eye: 2567 fixations, 786 mapped to words

In [6]:
events = pd.read_csv(
    "/store/users/xu/2025_MSc_b2b/ROAMM_preprocessing/outputs/roamm_fixation_events.csv"
)

counts = (
    events.dropna(subset=["word_key"])
    .groupby(["subject_id", "run_num", "word_key"])
    .size()
)

print(counts.value_counts().sort_index())
print("Words fixated more than once:", (counts > 1).sum())

1     154211
2      64651
3      21133
4       7501
5       2747
6       1184
7        537
8        245
9        143
10        66
11        45
12        21
13        18
14         6
15         5
16         1
17         7
18         2
19         1
Name: count, dtype: int64
Words fixated more than once: 98313

In [8]:
events = events.sort_values(
    ["subject_id", "run_num", "onset_s"]
).copy()

previous_word = events.groupby(
    ["subject_id", "run_num"]
)["word_key"].shift(1)

events["consecutive_refixation"] = (
    events["word_key"].notna()
    & events["word_key"].eq(previous_word)
)
print(events)

       subject_id  run_num       story_name  page eye     onset_s    offset_s  \
0       sub-10014        1            pluto   0.0   R   12.220262   12.931262
1       sub-10014        1            pluto   0.0   R   12.949263   13.236263
2       sub-10014        1            pluto   0.0   R   13.253262   13.369262
3       sub-10014        1            pluto   0.0   R   13.424263   13.567262
4       sub-10014        1            pluto   0.0   R   13.589262   13.748262
...           ...      ...              ...   ...  ..         ...         ...
411177  sub-10202        5  serena_williams   9.0   R  369.562300  369.752300
411178  sub-10202        5  serena_williams   9.0   R  369.785300  369.879300
411179  sub-10202        5  serena_williams   9.0   R  369.904300  370.076300
411180  sub-10202        5  serena_williams   9.0   R  370.108300  370.329300
411181  sub-10202        5  serena_williams   9.0   R  370.364300  371.044300

        duration_ms           word                              word_key  \
0             712.0            NaN                                   NaN
1             288.0        volume.  202ed870-fb4d-4f17-90d9-b9e119a96ae3
2             117.0        volume.  202ed870-fb4d-4f17-90d9-b9e119a96ae3
3             144.0  (minor-planet  43e85048-6af0-4195-8627-796a1189f9e8
4             160.0          Pluto  b73180a5-011d-42d5-8c12-2a4acb4344b4
...             ...            ...                                   ...
411177        191.0       Williams  04088ef2-f7ed-45c3-a4a3-0cc82c088af7
411178         95.0          third  69b89bfa-ea8b-4bc8-a1e8-b39046c44da3
411179        173.0     semifinals  a47de8af-174d-4840-ad5f-4af99d285d85
411180        222.0          Henin  995ed02f-f01f-49cb-a2fb-c73bbeb1cdb0
411181        681.0            NaN                                   NaN

        latency  consecutive_refixation
0          3129                   False
1          3316                   False
2          3394                    True
3          3438                   False
4          3480                   False
...         ...                     ...
411177    94609                   False
411178    94666                   False
411179    94697                   False
411180    94749                   False
411181    94814                   False

[411182 rows x 12 columns]

# Check fixation i+1

In [3]:
import pandas as pd

events = pd.read_csv(
    "/store/users/xu/2025_MSc_b2b/ROAMM_preprocessing/outputs/04_roamm_fixation_events.csv"
)

events = events.sort_values(["subject_id", "run_num", "onset_s"]).copy()

events["next_onset"] = events.groupby(
    ["subject_id", "run_num"]
)["onset_s"].shift(-1)

events["next_page"] = events.groupby(
    ["subject_id", "run_num"]
)["page"].shift(-1)

events["interval_ms"] = (
    events["next_onset"] - events["onset_s"]
) * 1000

page_boundaries = events[
    events["page"] != events["next_page"]
]

print(page_boundaries[
    ["subject_id", "run_num", "page",
     "next_page", "interval_ms"]
].head(20))

     subject_id  run_num  page  next_page  interval_ms
49    sub-10014        1   0.0        1.0      35142.0
239   sub-10014        1   1.0        2.0      17938.0
276   sub-10014        1   2.0        3.0      39370.0
417   sub-10014        1   3.0        4.0      26328.0
524   sub-10014        1   4.0        5.0      17378.0
570   sub-10014        1   5.0        6.0      38163.0
583   sub-10014        1   6.0        7.0      45884.0
690   sub-10014        1   7.0        8.0      36509.0
740   sub-10014        1   8.0        9.0      25570.0
823   sub-10014        1   9.0        NaN          NaN
843   sub-10014        2   0.0        1.0      48623.0
1037  sub-10014        2   1.0        2.0      11251.0
1164  sub-10014        2   2.0        3.0      26948.0
1392  sub-10014        2   3.0        4.0       1087.0
1607  sub-10014        2   4.0        5.0      24395.0
1822  sub-10014        2   5.0        6.0        912.0
2004  sub-10014        2   6.0        7.0        296.0
2149  sub-10014        2   7.0        8.0      16164.0
2224  sub-10014        2   8.0        9.0      36466.0
2410  sub-10014        2   9.0        NaN          NaN

In [4]:
short_boundaries = page_boundaries[
    (page_boundaries["interval_ms"] < 2000)
    & (page_boundaries["interval_ms"] >= 0)
].copy()

print(short_boundaries[
    ["subject_id", "run_num", "page", "next_page",
     "onset_s", "next_onset", "interval_ms"]
].to_string(index=False))

subject_id  run_num  page  next_page    onset_s  next_onset  interval_ms
 sub-10014        2   3.0        4.0 237.035853  238.122853       1087.0
 sub-10014        2   5.0        6.0 368.872853  369.784853        912.0
 sub-10014        2   6.0        7.0 415.333853  415.629853        296.0
 sub-10014        3   5.0        6.0 361.576622  361.751622        175.0
 sub-10014        4   0.0        1.0  55.423050   56.571050       1148.0
 sub-10014        4   2.0        3.0 128.074050  128.712050        638.0
 sub-10014        5   2.0        3.0 236.518253  237.312253        794.0
 sub-10014        5   3.0        4.0 298.235253  299.066253        831.0
 sub-10052        1   0.0        1.0  84.974788   86.289788       1315.0
 sub-10052        1   1.0        2.0 121.696787  122.143788        447.0
 sub-10052        1   2.0        3.0 164.548788  164.775787        227.0
 sub-10052        1   3.0        4.0 219.937788  220.337788        400.0
 sub-10052        1   4.0        5.0 244.584787  245.272787        688.0
 sub-10052        1   5.0        6.0 302.967787  303.444788        477.0
 sub-10052        1   6.0        7.0 332.941788  333.366788        425.0
 sub-10052        1   7.0        8.0 365.514788  365.830787        316.0
 sub-10052        2   0.0        1.0  74.746897   75.041897        295.0
 sub-10052        2   1.0        2.0 127.949897  128.213897        264.0
 sub-10052        2   3.0        4.0 215.723897  215.982897        259.0
 sub-10052        2   4.0        5.0 240.889897  241.383897        494.0
 sub-10052        2   5.0        6.0 289.870897  290.363897        493.0
 sub-10052        2   6.0        7.0 324.715897  325.266897        551.0
 sub-10052        2   7.0        8.0 364.369897  365.033897        664.0
 sub-10052        3   0.0        1.0  74.077728   74.275728        198.0
 sub-10052        3   2.0        3.0 169.831728  170.230728        399.0
 sub-10052        3   5.0        6.0 351.716728  352.180728        464.0
 sub-10052        3   6.0        7.0 410.759728  411.101728        342.0
 sub-10052        4   2.0        3.0 214.778306  215.138306        360.0
 sub-10052        4   3.0        4.0 266.030306  266.317306        287.0
 sub-10052        4   5.0        6.0 355.248306  355.428306        180.0
 sub-10052        4   7.0        8.0 472.484306  472.699306        215.0
 sub-10052        4   8.0        9.0 521.185306  521.390306        205.0
 sub-10052        5   1.0        2.0 150.921369  151.623369        702.0
 sub-10052        5   2.0        3.0 205.998369  206.468369        470.0
 sub-10052        5   6.0        7.0 422.385369  422.899369        514.0
 sub-10052        5   7.0        8.0 452.519369  452.809369        290.0
 sub-10052        5   8.0        9.0 476.803369  477.148369        345.0
 sub-10059        1   0.0        1.0  81.500025   81.925025        425.0
 sub-10059        1   1.0        2.0 147.736025  148.261025        525.0
 sub-10059        1   2.0        3.0 220.861025  221.302025        441.0
 sub-10059        1   3.0        4.0 282.302025  282.709025        407.0
 sub-10059        1   4.0        5.0 352.937025  353.485025        548.0
 sub-10059        1   5.0        6.0 439.723025  439.829025        106.0
 sub-10059        1   7.0        8.0 572.723025  573.060025        337.0
 sub-10059        1   8.0        9.0 635.527025  635.842025        315.0
 sub-10059        2   0.0        1.0  71.893894   72.457894        564.0
 sub-10059        2   1.0        2.0 126.112894  126.496894        384.0
 sub-10059        2   2.0        3.0 187.653894  188.146894        493.0
 sub-10059        2   3.0        4.0 252.408894  253.015894        607.0
 sub-10059        2   4.0        5.0 309.218894  310.059894        841.0
 sub-10059        2   6.0        7.0 441.537894  441.911894        374.0
 sub-10059        2   7.0        8.0 496.769894  496.884894        115.0
 sub-10059        2   8.0        9.0 550.783894  551.099894        316.0
 sub-10059        3   1.0        2.0 133.626734  134.083734        457.0
 sub-10059        3   3.0        4.0 259.644734  259.976734        332.0
 sub-10059        3   4.0        5.0 320.699734  320.851734        152.0
 sub-10059        3   5.0        6.0 384.184734  384.296734        112.0
 sub-10059        3   6.0        7.0 439.667734  440.244734        577.0
 sub-10059        3   8.0        9.0 562.034734  562.391734        357.0
 sub-10059        4   0.0        1.0  65.138913   65.659912        521.0
 sub-10059        4   1.0        2.0 129.048912  129.299913        251.0
 sub-10059        4   2.0        3.0 182.732913  182.948913        216.0
 sub-10059        4   3.0        4.0 237.339913  237.734913        395.0
 sub-10059        4   4.0        5.0 293.416913  294.074912        658.0
 sub-10059        4   5.0        6.0 359.843912  360.242913        399.0
 sub-10059        4   6.0        7.0 422.938913  423.427912        489.0
 sub-10059        4   8.0        9.0 543.296913  543.535912        239.0
 sub-10059        5   0.0        1.0  71.517525   71.669525        152.0
 sub-10059        5   1.0        2.0 135.526525  135.739525        213.0
 sub-10059        5   2.0        3.0 190.189525  190.398525        209.0
 sub-10059        5   3.0        4.0 241.857525  242.020525        163.0
 sub-10059        5   4.0        5.0 303.908525  304.582525        674.0
 sub-10059        5   5.0        6.0 362.131525  362.562525        431.0
 sub-10059        5   6.0        7.0 420.400525  420.610525        210.0
 sub-10059        5   7.0        8.0 474.017525  474.868525        851.0
 sub-10059        5   8.0        9.0 527.823525  528.320525        497.0
 sub-10073        1   0.0        1.0  72.416906   72.600906        184.0
 sub-10073        1   3.0        4.0 263.706906  263.864906        158.0
 sub-10073        1   4.0        5.0 327.491906  327.681906        190.0
 sub-10073        1   5.0        6.0 387.929906  388.250906        321.0
 sub-10073        1   7.0        8.0 509.664906  510.251906        587.0
 sub-10073        2   0.0        1.0  71.927331   72.140331        213.0
 sub-10073        2   1.0        2.0 139.545331  139.680331        135.0
 sub-10073        2   2.0        3.0 195.430331  195.621331        191.0
 sub-10073        2   3.0        4.0 239.615331  240.211331        596.0
 sub-10073        2   4.0        5.0 299.746331  300.216331        470.0
 sub-10073        2   5.0        6.0 350.744331  351.320331        576.0
 sub-10073        2   7.0        8.0 464.687331  465.111331        424.0
 sub-10073        2   8.0        9.0 515.186331  515.356331        170.0
 sub-10073        3   1.0        2.0 166.238109  167.457109       1219.0
 sub-10073        3   3.0        4.0 298.339109  299.135109        796.0
 sub-10073        3   4.0        5.0 355.059109  355.251109        192.0
 sub-10073        3   5.0        6.0 406.876109  407.239109        363.0
 sub-10073        3   6.0        7.0 464.934109  465.100109        166.0
 sub-10073        3   8.0        9.0 569.323109  569.992109        669.0
 sub-10073        4   1.0        2.0 139.750231  140.412231        662.0
 sub-10073        4   2.0        3.0 212.959231  213.265231        306.0
 sub-10073        4   3.0        4.0 264.563231  264.892231        329.0
 sub-10073        4   4.0        5.0 319.113231  319.501231        388.0
 sub-10073        4   5.0        6.0 367.264231  367.517231        253.0
 sub-10073        4   6.0        7.0 417.051231  417.655231        604.0
 sub-10073        4   8.0        9.0 523.360231  523.971231        611.0
 sub-10073        5   0.0        1.0  62.268350   63.327350       1059.0
 sub-10073        5   2.0        3.0 178.543350  179.312350        769.0
 sub-10073        5   4.0        5.0 300.051350  300.663350        612.0
 sub-10073        5   5.0        6.0 348.024350  348.142350        118.0
 sub-10073        5   6.0        7.0 401.331350  401.746350        415.0
 sub-10081        1   0.0        1.0  60.540731   60.700731        160.0
 sub-10081        1   1.0        2.0  69.831731   70.051731        220.0
 sub-10081        1   3.0        4.0 193.404731  193.619731        215.0
 sub-10081        1   8.0        9.0 457.670731  457.987731        317.0
 sub-10081        2   6.0        7.0 361.189028  361.332028        143.0
 sub-10081        2   7.0        8.0 402.807028  402.987028        180.0
 sub-10081        3   0.0        1.0  49.874375   50.171375        297.0
 sub-10081        3   2.0        3.0 140.490375  141.107375        617.0
 sub-10081        3   8.0        9.0 462.190375  462.659375        469.0
 sub-10081        4   0.0        1.0  45.734869   46.498869        764.0
 sub-10081        4   3.0        4.0 207.495869  207.876869        381.0
 sub-10081        4   4.0        5.0 255.174869  255.348869        174.0
 sub-10081        4   8.0        9.0 464.122869  464.644869        522.0
 sub-10081        5   1.0        2.0  99.827981  100.145981        318.0
 sub-10081        5   2.0        3.0 143.043981  143.276981        233.0
 sub-10081        5   4.0        5.0 242.941981  243.202981        261.0
 sub-10081        5   5.0        6.0 283.506981  283.994981        488.0
 sub-10081        5   6.0        7.0 318.490981  318.848981        358.0
 sub-10081        5   7.0        8.0 359.503981  359.783981        280.0
 sub-10084        1   0.0        1.0  70.066372   70.633372        567.0
 sub-10084        1   1.0        2.0 125.316372  126.128372        812.0
 sub-10084        1   3.0        4.0 241.882372  242.885372       1003.0
 sub-10084        1   8.0        9.0 504.605372  505.056372        451.0
 sub-10084        2   0.0        1.0  66.734072   67.484072        750.0
 sub-10084        2   1.0        2.0 110.636072  111.331072        695.0
 sub-10084        2   4.0        5.0 276.651072  277.426072        775.0
 sub-10084        2   6.0        7.0 376.552072  376.684072        132.0
 sub-10084        2   8.0        9.0 470.714072  470.898072        184.0
 sub-10084        3   1.0        2.0 112.482581  113.097581        615.0
 sub-10084        3   2.0        3.0 155.051581  155.608581        557.0
 sub-10084        3   3.0        4.0 204.461581  204.654581        193.0
 sub-10084        3   4.0        5.0 250.660581  251.303581        643.0
 sub-10084        3   6.0        7.0 347.643581  348.080581        437.0
 sub-10084        3   7.0        8.0 391.144581  391.691581        547.0
 sub-10084        4   4.0        5.0 294.012291  294.271291        259.0
 sub-10084        4   5.0        6.0 340.921291  341.071291        150.0
 sub-10084        5   0.0        1.0  65.038331   65.558331        520.0
 sub-10084        5   4.0        5.0 283.578331  284.323331        745.0
 sub-10084        5   5.0        6.0 332.155331  332.744331        589.0
 sub-10084        5   6.0        7.0 375.786331  375.941331        155.0
 sub-10085        1   2.0        3.0 177.670700  178.136700        466.0
 sub-10085        1   7.0        8.0 538.761700  539.110700        349.0
 sub-10085        2   2.0        3.0 185.035841  185.514841        479.0
 sub-10085        3   1.0        2.0 110.315300  110.866300        551.0
 sub-10085        4   0.0        1.0  76.726719   77.592719        866.0
 sub-10085        4   3.0        4.0 276.266719  276.815719        549.0
 sub-10085        4   5.0        6.0 383.342719  383.504719        162.0
 sub-10085        4   7.0        8.0 509.219719  509.842719        623.0
 sub-10085        5   1.0        2.0 106.105713  106.774713        669.0
 sub-10085        5   4.0        5.0 303.641713  304.343712        702.0
 sub-10085        5   7.0        8.0 449.936712  450.093712        157.0
 sub-10089        1   0.0        1.0  80.087269   80.859269        772.0
 sub-10089        1   1.0        2.0 144.953269  145.643269        690.0
 sub-10089        1   4.0        5.0 359.596269  360.017269        421.0
 sub-10089        1   6.0        7.0 494.308269  494.743269        435.0
 sub-10089        1   8.0        9.0 616.218269  617.410269       1192.0
 sub-10089        2   0.0        1.0  72.955400   73.229400        274.0
 sub-10089        2   2.0        3.0 205.478400  206.468400        990.0
 sub-10089        2   3.0        4.0 261.511400  262.140400        629.0
 sub-10089        2   4.0        5.0 314.179400  315.017400        838.0
 sub-10089        2   8.0        9.0 571.180400  572.055400        875.0
 sub-10089        3   0.0        1.0  73.668216   74.758216       1090.0
 sub-10089        3   1.0        2.0 130.670216  131.280216        610.0
 sub-10089        3   2.0        3.0 173.102216  173.955216        853.0
 sub-10089        3   3.0        4.0 230.066216  230.660216        594.0
 sub-10089        3   4.0        5.0 292.252216  292.418216        166.0
 sub-10089        3   5.0        6.0 357.229216  357.899216        670.0
 sub-10089        3   6.0        7.0 409.457216  410.779216       1322.0
 sub-10089        3   7.0        8.0 472.528216  473.430216        902.0
 sub-10089        3   8.0        9.0 526.230216  526.603216        373.0
 sub-10089        4   0.0        1.0  60.491966   61.301966        810.0
 sub-10089        4   1.0        2.0 114.888966  115.401966        513.0
 sub-10089        4   2.0        3.0 175.787966  176.558966        771.0
 sub-10089        4   3.0        4.0 236.032966  236.825966        793.0
 sub-10089        4   4.0        5.0 293.589966  294.312966        723.0
 sub-10089        4   5.0        6.0 340.300966  341.114966        814.0
 sub-10089        4   6.0        7.0 392.004966  392.772966        768.0
 sub-10089        4   8.0        9.0 505.664966  506.510966        846.0
 sub-10089        5   0.0        1.0  63.079278   63.805278        726.0
 sub-10089        5   1.0        2.0 120.674278  121.651278        977.0
 sub-10089        5   2.0        3.0 173.422278  174.209278        787.0
 sub-10089        5   3.0        4.0 231.552278  232.364278        812.0
 sub-10089        5   4.0        5.0 295.481278  296.495278       1014.0
 sub-10089        5   6.0        7.0 418.991278  419.940278        949.0
 sub-10089        5   7.0        8.0 473.371278  474.178278        807.0
 sub-10089        5   8.0        9.0 526.368278  527.600278       1232.0
 sub-10094        1   0.0        1.0  75.351669   75.767669        416.0
 sub-10094        1   1.0        2.0 134.859669  135.504669        645.0
 sub-10094        1   2.0        3.0 195.310669  195.914669        604.0
 sub-10094        1   3.0        4.0 256.090669  256.269669        179.0
 sub-10094        1   4.0        5.0 318.504669  318.831669        327.0
 sub-10094        1   5.0        6.0 374.905669  375.662669        757.0
 sub-10094        1   6.0        7.0 426.838669  427.067669        229.0
 sub-10094        1   7.0        8.0 474.038669  474.196669        158.0
 sub-10094        1   8.0        9.0 530.750669  531.516669        766.0
 sub-10094        2   0.0        1.0  60.078881   60.922881        844.0
 sub-10094        2   1.0        2.0 117.520881  117.888881        368.0
 sub-10094        2   2.0        3.0 176.396881  177.209881        813.0
 sub-10094        2   3.0        4.0 238.306881  238.932881        626.0
 sub-10094        2   4.0        5.0 292.689881  293.562881        873.0
 sub-10094        2   5.0        6.0 341.345881  342.576881       1231.0
 sub-10094        2   6.0        7.0 393.929881  394.753881        824.0
 sub-10094        2   7.0        8.0 443.936881  444.822881        886.0
 sub-10094        2   8.0        9.0 498.038881  498.412881        374.0
 sub-10094        3   0.0        1.0  61.514344   62.260344        746.0
 sub-10094        3   1.0        2.0 118.575344  119.392344        817.0
 sub-10094        3   2.0        3.0 178.813344  179.587344        774.0
 sub-10094        3   3.0        4.0 241.332344  241.519344        187.0
 sub-10094        3   4.0        5.0 299.374344  300.405344       1031.0
 sub-10094        3   5.0        6.0 356.307344  357.272344        965.0
 sub-10094        3   7.0        8.0 485.161344  485.733344        572.0
 sub-10094        3   8.0        9.0 537.612344  538.373344        761.0
 sub-10094        4   0.0        1.0  65.372422   66.123422        751.0
 sub-10094        4   1.0        2.0 122.060422  122.590422        530.0
 sub-10094        4   2.0        3.0 167.119422  167.833422        714.0
 sub-10094        4   3.0        4.0 220.057422  220.318422        261.0
 sub-10094        4   4.0        5.0 273.824422  274.262422        438.0
 sub-10094        4   5.0        6.0 329.550422  329.765422        215.0
 sub-10094        4   6.0        7.0 380.789422  381.623422        834.0
 sub-10094        4   7.0        8.0 434.078422  434.838422        760.0
 sub-10094        4   8.0        9.0 493.981422  494.799422        818.0
 sub-10094        5   0.0        1.0  44.313288   45.014288        701.0
 sub-10094        5   1.0        2.0  95.965288   96.250287        285.0
 sub-10094        5   2.0        3.0 148.652287  149.322288        670.0
 sub-10094        5   3.0        4.0 191.013287  191.953288        940.0
 sub-10094        5   4.0        5.0 250.729288  250.920288        191.0
 sub-10094        5   5.0        6.0 299.543287  299.729288        186.0
 sub-10094        5   6.0        7.0 345.939288  346.570287        631.0
 sub-10094        5   7.0        8.0 403.329287  404.132287        803.0
 sub-10094        5   8.0        9.0 451.097287  451.562287        465.0
 sub-10100        1   3.0        4.0 289.105481  289.459481        354.0
 sub-10100        1   4.0        5.0 340.594481  340.981481        387.0
 sub-10100        1   6.0        7.0 470.786481  471.187481        401.0
 sub-10100        3   0.0        1.0  65.679656   65.975656        296.0
 sub-10100        3   6.0        7.0 410.964656  411.990656       1026.0
 sub-10100        3   8.0        9.0 504.879656  505.075656        196.0
 sub-10100        4   0.0        1.0  73.772028   74.109028        337.0
 sub-10100        4   7.0        8.0 465.355028  465.719028        364.0
 sub-10100        5   0.0        1.0  63.367234   63.513234        146.0
 sub-10103        1   0.0        1.0  72.791603   73.403603        612.0
 sub-10103        1   1.0        2.0 141.248603  141.426603        178.0
 sub-10103        1   2.0        3.0 198.139603  199.041603        902.0
 sub-10103        1   4.0        5.0 309.901603  310.369603        468.0
 sub-10103        1   6.0        7.0 421.244603  421.443603        199.0
 sub-10103        1   7.0        8.0 479.738603  480.217603        479.0
 sub-10103        1   8.0        9.0 527.995603  528.728603        733.0
 sub-10103        2   0.0        1.0  65.542987   65.726988        184.0
 sub-10103        2   1.0        2.0 122.085988  122.845987        760.0
 sub-10103        2   2.0        3.0 172.119987  172.297988        178.0
 sub-10103        2   3.0        4.0 225.238987  225.435988        197.0
 sub-10103        2   5.0        6.0 334.204987  334.676987        472.0
 sub-10103        2   6.0        7.0 382.118988  382.533988        415.0
 sub-10103        2   7.0        8.0 436.385987  436.811987        426.0
 sub-10103        2   8.0        9.0 484.205987  484.735988        530.0
 sub-10103        3   0.0        1.0  58.239269   58.630269        391.0
 sub-10103        3   1.0        2.0 106.956269  107.479269        523.0
 sub-10103        3   2.0        3.0 165.203269  165.993269        790.0
 sub-10103        3   3.0        4.0 220.332269  220.666269        334.0
 sub-10103        3   6.0        7.0 389.143269  389.794269        651.0
 sub-10103        3   8.0        9.0 516.954269  517.419269        465.0
 sub-10103        4   0.0        1.0  60.394838   60.556838        162.0
 sub-10103        4   2.0        3.0 153.033838  153.190838        157.0
 sub-10103        4   3.0        4.0 200.370837  200.484838        114.0
 sub-10103        4   5.0        6.0 295.828838  296.631838        803.0
 sub-10103        4   6.0        7.0 333.847837  334.414837        567.0

In [5]:
example = events[
    (events["subject_id"] == "sub-10014")
    & (events["run_num"] == 2)
    & (events["page"].isin([6, 7]))
]

print(
    example[
        ["page", "onset_s", "duration_ms", "word"]
    ].tail(20).to_string(index=False)
)

 page    onset_s  duration_ms         word
  7.0 447.220853        195.0           II
  7.0 447.445853        224.0 (1552-1612),
  7.0 447.706853        223.0         paid
  7.0 447.953853        215.0         gold
  7.0 448.183853        170.0       claims
  7.0 448.366853         59.0       claims
  7.0 448.518853        167.0     belonged
  7.0 448.701853         42.0     belonged
  7.0 448.775853        201.0          it.
  7.0 448.997853        146.0          it.
  7.0 449.180853        239.0           kg
  7.0 449.443853        248.0        gold)
  7.0 449.713853        221.0        gold)
  7.0 449.975853        157.0         book
  7.0 450.156853        367.0         then
  7.0 450.543853        194.0         book
  7.0 450.770853        224.0        given
  7.0 451.023853        519.0         lent
  7.0 451.555853        266.0           to
  7.0 451.846853        347.0          NaN

In [6]:
page6 = example[example["page"] == 6]
page7 = example[example["page"] == 7]

print("Last fixations on page 6:")
print(page6.tail(5)[["onset_s", "duration_ms", "word"]])

print("\nFirst fixations on page 7:")
print(page7.head(5)[["onset_s", "duration_ms", "word"]])

Last fixations on page 6:
         onset_s  duration_ms          word
2000  414.175853        175.0       remains
2001  414.366853        139.0       remains
2002  414.801853         74.0  speculative.
2003  414.902853        408.0  speculative.
2004  415.333853        233.0  speculative.

First fixations on page 7:
         onset_s  duration_ms word
2005  415.629853        526.0  NaN
2006  416.253853        211.0  NaN
2007  416.480853        120.0  NaN
2008  416.629853        166.0  NaN
2009  418.669853         83.0  NaN

In [7]:
page7[page7["word"].notna()][
    ["onset_s", "duration_ms", "word"]
].head(10)

         onset_s  duration_ms      word
2010  418.934853        275.0       the
2011  419.238853         37.0  unknown,
2012  419.483853        208.0  unknown,
2013  419.718853        211.0    though
2014  419.960853        142.0      text
2015  420.280853         21.0      text
2016  420.392853        208.0        of
2017  420.628853        204.0     early
2018  420.861853        175.0        of
2019  421.064853        186.0      book

# Check EEG data

In [2]:
from pathlib import Path
import pandas as pd

file = Path(
    "/scratch/data/ROAMM/derivatives/synced/"
    "sub-10141/sub-10141_task-ReMind_run-03_mldata.pkl"
)

df_check = pd.read_pickle(file)

In [3]:
print(df_check.columns.tolist())

print(df_check["first_pass_reading"].value_counts(dropna=False))

['Fp1', 'AF7', 'AF3', 'F1', 'F3', 'F5', 'F7', 'FT7', 'FC5', 'FC3', 'FC1', 'C1', 'C3', 'C5', 'T7', 'TP7', 'CP5', 'CP3', 'CP1', 'P1', 'P3', 'P5', 'P7', 'P9', 'PO7', 'PO3', 'O1', 'Iz', 'Oz', 'POz', 'Pz', 'CPz', 'Fpz', 'Fp2', 'AF8', 'AF4', 'Afz', 'Fz', 'F2', 'F4', 'F6', 'F8', 'FT8', 'FC6', 'FC4', 'FC2', 'FCz', 'Cz', 'C2', 'C4', 'C6', 'T8', 'TP8', 'CP6', 'CP4', 'CP2', 'P2', 'P4', 'P6', 'P8', 'P10', 'PO8', 'PO4', 'O2', 'time', 'sfreq', 'first_pass_reading', 'page_num', 'page_start', 'page_end', 'page_dur', 'is_mw', 'mw_onset', 'mw_offset', 'mw_dur', 'run_num', 'story_name', 'is_fix', 'fix_R_eye', 'fix_R_tStart', 'fix_R_tEnd', 'fix_R_duration', 'fix_R_xAvg', 'fix_R_yAvg', 'fix_R_pupilAvg', 'fix_R_fixed_word', 'fix_R_fixed_word_key', 'is_blink', 'blink_L_eye', 'blink_L_tStart', 'blink_L_tEnd', 'blink_L_duration', 'blink_R_eye', 'blink_R_tStart', 'blink_R_tEnd', 'blink_R_duration', 'is_sacc', 'sacc_L_eye', 'sacc_L_tStart', 'sacc_L_tEnd', 'sacc_L_duration', 'sacc_L_xStart', 'sacc_L_yStart', 'sacc_L_xEnd', 'sacc_L_yEnd', 'sacc_L_ampDeg', 'sacc_L_vPeak', 'sacc_R_eye', 'sacc_R_tStart', 'sacc_R_tEnd', 'sacc_R_duration', 'sacc_R_xStart', 'sacc_R_yStart', 'sacc_R_xEnd', 'sacc_R_yEnd', 'sacc_R_ampDeg', 'sacc_R_vPeak', 'tSample', 'LX', 'LY', 'LPupil', 'RX', 'RY', 'RPupil', 'blink_interp_LX', 'blink_interp_LY', 'blink_interp_LPupil', 'blink_interp_RX', 'blink_interp_RY', 'blink_interp_RPupil']
first_pass_reading
NaN     118895
True     92049
Name: count, dtype: int64

In [5]:
dt = df_check["time"].diff().dropna()

print(dt.describe())
print("Largest gaps (seconds):")
print(dt.nlargest(5))

count    210943.000000
mean          0.003906
std           0.000000
min           0.003906
25%           0.003906
50%           0.003906
75%           0.003906
max           0.003906
Name: time, dtype: float64
Largest gaps (seconds):
1    0.003906
2    0.003906
3    0.003906
4    0.003906
5    0.003906
Name: time, dtype: float64

# Do we need neareast sample() in 04_prepare_fixation_events

In [6]:
from pathlib import Path
import pandas as pd
import numpy as np

file = next(
    Path("/scratch/data/ROAMM/derivatives/synced")
    .glob("sub-*/*_mldata.pkl")
)

df = pd.read_pickle(file)

print(file)
print(df.shape)
print(df[["time", "fix_R_tStart"]].head(10))

/scratch/data/ROAMM/derivatives/synced/sub-10158/sub-10158_task-ReMind_run-02_mldata.pkl
(223488, 139)
       time  fix_R_tStart
0  0.000000           NaN
1  0.003906           NaN
2  0.007812           NaN
3  0.011719           NaN
4  0.015625           NaN
5  0.019531           NaN
6  0.023438           NaN
7  0.027344           NaN
8  0.031250           NaN
9  0.035156           NaN

In [7]:
fixations = df.loc[
    df["fix_R_tStart"].notna(),
    ["time", "fix_R_tStart"]
].copy()

print(fixations.head(10))

        time  fix_R_tStart
31  0.121094      0.117822
32  0.125000      0.117822
33  0.128906      0.117822
34  0.132812      0.117822
35  0.136719      0.117822
36  0.140625      0.117822
37  0.144531      0.117822
38  0.148438      0.117822
39  0.152344      0.117822
40  0.156250      0.117822

In [8]:
fixations["difference_ms"] = (
    fixations["time"] - fixations["fix_R_tStart"]
) * 1000

print(fixations.head(20))
print(fixations["difference_ms"].describe())

        time  fix_R_tStart  difference_ms
31  0.121094      0.117822       3.271875
32  0.125000      0.117822       7.178125
33  0.128906      0.117822      11.084375
34  0.132812      0.117822      14.990625
35  0.136719      0.117822      18.896875
36  0.140625      0.117822      22.803125
37  0.144531      0.117822      26.709375
38  0.148438      0.117822      30.615625
39  0.152344      0.117822      34.521875
40  0.156250      0.117822      38.428125
41  0.160156      0.117822      42.334375
42  0.164062      0.117822      46.240625
43  0.167969      0.117822      50.146875
44  0.171875      0.117822      54.053125
45  0.175781      0.117822      57.959375
46  0.179688      0.117822      61.865625
47  0.183594      0.117822      65.771875
48  0.187500      0.117822      69.678125
49  0.191406      0.117822      73.584375
50  0.195312      0.117822      77.490625
count    192911.000000
mean        150.329406
std         130.573885
min           0.021875
25%          60.865625
50%         123.553125
75%         202.553125
max        1662.646875
Name: difference_ms, dtype: float64

# check synchronized DataFrame has regular time intervals.

In [3]:
from pathlib import Path
import pandas as pd
import numpy as np

filepath = "/scratch/data/ROAMM/derivatives/synced/sub-10014/sub-10014_task-ReMind_run-01_mldata.pkl"
df = pd.read_pickle(filepath)

time = df["time"].to_numpy()
dt = np.diff(time)

print("Number of samples:", len(time))
print("Median sample interval:", np.median(dt))
print("Expected interval:", 1 / 256)
print("Largest sample interval:", np.max(dt))
print("Number of gaps > 2 samples:", np.sum(dt > 2 / 256))

Number of samples: 168704
Median sample interval: 0.00390625
Expected interval: 0.00390625
Largest sample interval: 0.00390625
Number of gaps > 2 samples: 0